export const people = [
  {
    id: 1,
    first_name: "Kitti",
    last_name: "Ritchard",
    email: "kritchard0@ucla.edu",
    gender: "Female",
    date_of_birth: "2002-11-30T06:50:42Z",
  },
  {
    id: 2,
    first_name: "Molly",
    last_name: "Baff",
    email: "mbaff1@cnn.com",
    gender: "Female",
    date_of_birth: "2000-12-24T12:07:27Z",
  },
  {
    id: 3,
    first_name: "Abrahan",
    last_name: "Dance",
    email: "adance2@ucoz.ru",
    gender: "Male",
    date_of_birth: "2018-03-19T12:29:57Z",
  },
  {
    id: 4,
    first_name: "Delcina",
    last_name: "Buckle",
    email: "dbuckle3@oakley.com",
    gender: "Female",
    date_of_birth: "2010-12-26T20:21:46Z",
  },
  {
    id: 5,
    first_name: "Wheeler",
    last_name: "Hickisson",
    email: "whickisson4@hud.gov",
    gender: "Male",
    date_of_birth: "2005-12-06T00:58:11Z",
  },
  {
    id: 6,
    first_name: "Vivienne",
    last_name: "Bowhay",
    email: "vbowhay5@slashdot.org",
    gender: "Female",
    date_of_birth: "2010-12-24T04:44:16Z",
  },
  {
    id: 7,
    first_name: "Anneliese",
    last_name: "Jaan",
    email: "ajaan6@freewebs.com",
    gender: "Female",
    date_of_birth: "2018-08-13T07:27:34Z",
  },
];

export type Person = (typeof people)[number];
